name: gradio-llm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.0  # Choose a version compatible with most of your packages
  - aiofiles=23.2.1
  - aiohttp=3.8.6
  - aiosignal=1.3.1
  - altair=5.1.2
  - annotated-types=0.6.0
  - anyio=3.7.1
  - async-timeout=4.0.3
  - attrs=23.1.0
  - certifi=2023.7.22
  - charset-normalizer=3.3.0
  - click=8.1.7
  - cmake=3.27.6
  - contourpy=1.1.1
  - cycler=0.12.1
  - dataclasses-json=0.6.1
  - fastapi=0.103.2
  - ffmpy=0.3.1
  - filelock=3.12.4
  - fonttools=4.43.1
  - frozenlist=1.4.0
  - fsspec=2023.9.2
  - gradio=3.46.1
  - gradio-client=0.5.3
  - greenlet=3.0.0  # Check for platform compatibility
  - h11=0.14.0
  - httpcore=0.18.0
  - httpx=0.25.0
  - huggingface-hub=0.17.3
  - idna=3.4
  - importlib-resources=6.1.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jsonschema=4.19.1
  - jsonschema-specifications=2023.7.1
  - kiwisolver=1.4.5
  - langchain=0.0.308
  - langsmith=0.0.43
  - lit=17.0.2
  - markupsafe=2.1.3
  - marshmallow=3.20.1
  - matplotlib=3.8.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - mypy-extensions=1.0.0
  - networkx=3.1
  - nltk=3.8.1
  - numpy=1.26.0
  - orjson=3.9.8
  - packaging=23.2
  - pandas=2.1.1
  - pillow=10.0.1
  - pydantic=2.4.2
  - pydantic-core=2.10.1
  - pydub=0.25.1
  - pyparsing=3.1.1
  - python-dateutil=2.8.2
  - python-dotenv=1.0.0
  - python-multipart=0.0.6
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - redis=5.0.1
  - regex=2023.10.3
  - requests=2.31.0
  - rpds-py=0.10.6
  - safetensors=0.4.0
  - scikit-learn=1.3.1
  - scipy=1.11.3
  - semantic-version=2.10.0
  - sentence-transformers=2.2.2
  - sentencepiece=0.1.99
  - six=1.16.0
  - sniffio=1.3.0
  - sqlalchemy=2.0.21
  - starlette=0.27.0
  - sympy=1.12
  - tenacity=8.2.3
  - text-generation=0.6.1
  - threadpoolctl=3.2.0
  - tokenizers=0.14.1
  - toolz=0.12.0
  - torch=2.0.1  # For CUDA 11.8, install using pip or specify the channel
  - torchvision=0.15.2  # For CUDA 11.8, install using pip or specify the channel
  - tqdm=4.66.1
  - transformers=4.34.0
  - triton=2.0.0  # Check for platform compatibility
  - typing-extensions=4.8.0
  - typing-inspect=0.9.0
  - tzdata=2023.3
  - urllib3=2.0.6
  - uvicorn=0.23.2
  - websockets=11.0.3
  - yarl=1.9.2
